# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mrerrormessage.github.com
subtitle: A Little Bit of Everything
author: Robert Grider
simple_search: http://google.com/search
url: http://mrerrormessage.github.com
future: false
description:
email: mrerrormessage@gmail.com
twitter_username: mrerrormessage
github_username:  mrerrormessage

# Build settings
markdown: kramdown
